# -*- coding: utf-8 -*-
"""storage bot..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nwy4An1894LQrkY06x515W85-r6waG9O
"""

import telebot
import logging
import time
import os
import sqlite3
from datetime import datetime
from openpyxl import Workbook

TOKEN = "TOKEN"
ADMIN_ID = 8369307958

bot = telebot.TeleBot(TOKEN)
logging.basicConfig(level=logging.INFO)

os.makedirs("downloads/audio", exist_ok=True)
os.makedirs("downloads/documents", exist_ok=True)
os.makedirs("downloads/images", exist_ok=True)

conn = sqlite3.connect("bot.db", check_same_thread=False)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY,
    name TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    file_name TEXT,
    file_type TEXT,
    file_size INTEGER,
    tag TEXT,
    date TEXT
)
""")

conn.commit()


def is_admin(user_id):
    return user_id == ADMIN_ID

def save_user(user_id, name):
    cursor.execute("INSERT OR IGNORE INTO users VALUES (?, ?)", (user_id, name))
    conn.commit()

def save_file(user_id, file_name, file_type, file_size, tag):
    cursor.execute("""
    INSERT INTO files (user_id, file_name, file_type, file_size, tag, date)
    VALUES (?, ?, ?, ?, ?, ?)
    """, (user_id, file_name, file_type, file_size, tag,
          datetime.now().strftime("%Y-%m-%d %H:%M")))
    conn.commit()

@bot.message_handler(commands=['start'])
def start(message):
    save_user(message.from_user.id, message.from_user.first_name)
    bot.send_message(
        message.chat.id,
        " Welcome!\n\n"
        "Send files with a tag.\n\n"
        "Examples:\n"
        "CV (for resume)\n"
        "REPORT (for school/work)\n"
        "PERSONAL\n\n"
        "Commands:\n"
        "/search keyword\n"
        "/mystats\n"
        "/delete filename"
    )

@bot.message_handler(commands=['help'])
def help_cmd(message):
    bot.send_message(
        message.chat.id,
        " How to use:\n"
        "Send file + caption (tag)\n\n"
        "Example:\n"
        "CV myfile.pdf\n\n"
        "Commands:\n"
        "/search keyword\n"
        "/mystats\n"
        "/delete filename"
    )

@bot.message_handler(commands=['mystats'])
def mystats(message):
    cursor.execute("SELECT COUNT(*) FROM files WHERE user_id=?", (message.from_user.id,))
    count = cursor.fetchone()[0]
    bot.send_message(message.chat.id, f"You uploaded {count} files")



@bot.message_handler(commands=['search'])
def search(message):
    keyword = message.text.replace("/search", "").strip().lower()

    cursor.execute("""
    SELECT file_name, tag FROM files
    WHERE (file_name LIKE ? OR tag LIKE ?) AND user_id = ?
    """, (f"%{keyword}%", f"%{keyword}%", message.from_user.id))

    results = cursor.fetchall()

    if results:
        text = "Results:\n"
        for r in results[:10]:
            text += f"{r[0]} ({r[1]})\n"
        bot.send_message(message.chat.id, text)
    else:
        bot.send_message(message.chat.id, " No results found")


# 📄 DOCUMENT
@bot.message_handler(content_types=['document'])
def handle_document(message):
    try:
        caption = message.caption or "general"
        tag = caption.split()[0].lower()

        file_info = bot.get_file(message.document.file_id)
        downloaded = bot.download_file(file_info.file_path)

        file_name = message.document.file_name
        file_path = f"downloads/documents/{file_name}"

        with open(file_path, 'wb') as f:
            f.write(downloaded)

        save_file(message.from_user.id, file_name, "document",
                  message.document.file_size, tag)

        bot.reply_to(message, f"📄 Saved: {file_name} ({tag})")

    except Exception as e:
        logging.error(e)

# 🎧 AUDIO
@bot.message_handler(content_types=['audio'])
def handle_audio(message):
    try:
        file_info = bot.get_file(message.audio.file_id)
        downloaded = bot.download_file(file_info.file_path)

        file_name = f"{message.audio.file_id}.mp3"
        file_path = f"downloads/audio/{file_name}"

        with open(file_path, 'wb') as f:
            f.write(downloaded)

        save_file(message.from_user.id, file_name, "audio",
                  message.audio.file_size, "audio")

        bot.reply_to(message, "🎧 Audio saved")

    except Exception as e:
        logging.error(e)

# 📸 IMAGE
@bot.message_handler(content_types=['photo'])
def handle_photo(message):
    try:
        file_id = message.photo[-1].file_id
        file_info = bot.get_file(file_id)
        downloaded = bot.download_file(file_info.file_path)

        caption = message.caption or "image"
        tag = caption.split()[0].lower()

        file_name = f"{file_id}.jpg"
        file_path = f"downloads/images/{file_name}"

        with open(file_path, 'wb') as f:
            f.write(downloaded)

        save_file(message.from_user.id, file_name, "image",
                  file_info.file_size, tag)

        bot.reply_to(message, f"📸 Image saved ({tag})")

    except Exception as e:
        logging.error(e)

#  DELETE

@bot.message_handler(commands=['delete'])
def delete_file(message):
    try:
        target = message.text.replace("/delete", "").strip()

        if not target:
            return bot.reply_to(message, "⚠️ Usage: /delete filename")

        cursor.execute("""
        SELECT file_type FROM files
        WHERE file_name=? AND user_id=?
        """, (target, message.from_user.id))

        result = cursor.fetchone()

        if result:
            file_type = result[0]

            folder_map = {
                "document": "documents",
                "audio": "audio",
                "image": "images"
            }

            folder = folder_map.get(file_type, "documents")
            path = f"downloads/{folder}/{target}"

            if os.path.exists(path):
                os.remove(path)

            cursor.execute("""
            DELETE FROM files
            WHERE file_name=? AND user_id=?
            """, (target, message.from_user.id))
            conn.commit()

            bot.reply_to(message, f"🗑️ Deleted: {target}")
        else:
            bot.reply_to(message, "❌ File not found")

    except Exception as e:
        logging.error(e)

# ADMIN

@bot.message_handler(commands=['admin'])
def admin_panel(message):
    if not is_admin(message.from_user.id):
        return bot.send_message(message.chat.id, "❌ Access denied")

    cursor.execute("SELECT COUNT(*) FROM users")
    users = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM files")
    files = cursor.fetchone()[0]

    bot.send_message(
        message.chat.id,
        f"Admin Dashboard\nUsers: {users}\nFiles: {files}\n\n/export"
    )

# =EXPORT

@bot.message_handler(commands=['export'])
def export_data(message):
    if not is_admin(message.from_user.id):
        return bot.send_message(message.chat.id, "❌ Access denied")

    wb = Workbook()
    ws = wb.active
    ws.append(["User ID", "File Name", "Type", "Size", "Tag", "Date"])

    cursor.execute("SELECT user_id, file_name, file_type, file_size, tag, date FROM files")
    for row in cursor.fetchall():
        ws.append(row)

    file_name = "export.xlsx"
    wb.save(file_name)

    with open(file_name, 'rb') as f:
        bot.send_document(message.chat.id, f)


@bot.message_handler(func=lambda m: True)
def fallback(message):
    bot.reply_to(message, "Send a file or use /help")

def start_bot():
    while True:
        try:
            print("Bot running...")
            bot.infinity_polling()
        except Exception as e:
            print("Error:", e)
            time.sleep(5)

if __name__ == "__main__":
    start_bot()
